### ISSUE TITLE
Crash upon game start.

### ISSUE THREAD

**Issue by MBMadness** [KallenKas024/Metaphysics#2]
Whenever I seem to use this (Cryptography 0.0.4) the mod seems to be rejected by minecraft, I am able to enter the game, but afterwards, when I enter a world, the game instantly crashes, this seems to only happen when I have this mod installed.

Here is the crash report.

[crash-2024-11-17_13.54.15-client.txt](https://github.com/user-attachments/files/17791985/crash-2024-11-17_13.54.15-client.txt)

**Comment by super95shao** [comment]
Try updating Metaphysics to 0.0.5,
it requires a new version of cc:tweaked

**Comment by MBMadness** [comment]
This solved the issue, you're a lifesaver shao, your FCS is amazing!!
